"""ProofFrame: Rust-native contracts, canonical fingerprints, and proof receipts."""

from ._proofframe import __version__
from .acceptance import accept_file, verify_acceptance
from .api import (
    assemble_evidence_unchecked,
    check,
    check_partitions,
    check_partitions_with_evidence,
    check_with_evidence,
    detect_leakage,
    diff,
    fingerprint,
    generate_keypair,
    profile,
    scan_pii,
    sign_evidence,
    sign_receipt,
    suggest_contract,
    validate,
    verify_receipt,
)
from .errors import (
    ContractError,
    CorruptDataError,
    ProofFrameArrowError,
    ProofFrameCorruptDataError,
    ProofFrameError,
    ProofFrameIoError,
    ReceiptError,
    ResourceLimitError,
    SchemaError,
)
from .review import review

__all__ = [
    "ContractError",
    "CorruptDataError",
    "ProofFrameArrowError",
    "ProofFrameCorruptDataError",
    "ProofFrameError",
    "ProofFrameIoError",
    "ReceiptError",
    "ResourceLimitError",
    "SchemaError",
    "__version__",
    "accept_file",
    "assemble_evidence_unchecked",
    "check",
    "check_partitions",
    "check_partitions_with_evidence",
    "check_with_evidence",
    "detect_leakage",
    "diff",
    "fingerprint",
    "generate_keypair",
    "profile",
    "review",
    "scan_pii",
    "sign_evidence",
    "sign_receipt",
    "suggest_contract",
    "validate",
    "verify_acceptance",
    "verify_receipt",
]
